import Menu from "@componets/Menu";
import Profil from "@componets/Profil";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faLinkedin,
  faGithub,
  faPinterest,
} from "@fortawesome/free-brands-svg-icons";
import { faDownload } from "@fortawesome/free-solid-svg-icons";
import Head from "next/head";
import React, { useState } from "react";
import styles from "./Container.module.scss";
import Link from "next/link";
import cn from "classnames";
import { useRouter } from "next/router";
import useMedia from "use-media";

type Props = {
  headerTitle?: string;
  children: React.ReactElement;
};

const Container: React.FC<Props> = ({ headerTitle, children }) => {
  const date = new Date().getFullYear();
  const [activeMenu, setActiveMenu] = useState(false);
  const router = useRouter();
  const isMobile = useMedia({ maxWidth: "575.98px" });
  return (
    <section className={styles.container}>
      <Head>
        <title>Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapperContainer}>
        <div
          className={cn({
            [styles.infoBar]: true,
            [styles.show]: activeMenu,
          })}
        >
          <Profil />
          {isMobile ? (
            <div>
              <ul className={styles.menu}>
                <li className={styles.menuItem}>
                  <Link href="/">
                    <a className={router.pathname == "/" ? styles.active : ""}>
                      Home
                    </a>
                  </Link>
                </li>
                <li className={styles.menuItem}>
                  <Link href="/about">
                    <a
                      className={
                        router.pathname == "/about" ? styles.active : ""
                      }
                    >
                      About Me
                    </a>
                  </Link>
                </li>
                <li className={styles.menuItem}>
                  <Link href="/resume">
                    <a
                      className={
                        router.pathname == "/resume" ? styles.active : ""
                      }
                    >
                      Resume
                    </a>
                  </Link>
                </li>
                <li className={styles.menuItem}>
                  <Link href="/contact">
                    <a
                      className={
                        router.pathname == "/contact" ? styles.active : ""
                      }
                    >
                      Contact Us
                    </a>
                  </Link>
                </li>
                <li className={styles.menuItem}>
                  <Link href="/portfolio">
                    <a
                      className={
                        router.pathname == "/portfolio" ? styles.active : ""
                      }
                    >
                      Portfolio
                    </a>
                  </Link>
                </li>
              </ul>
            </div>
          ) : null}

          <div className={styles.socialMedia}>
            <Link href="https://github.com/resaproject11" passHref>
              <a target="_blank" className={styles.socialIcon}>
                <FontAwesomeIcon
                  icon={faGithub}
                  size={isMobile ? "1x" : "2x"}
                />
              </a>
            </Link>
            <Link href="https://www.linkedin.com/in/resaabdilah/" passHref>
              <a target="_blank" className={styles.socialIcon}>
                <FontAwesomeIcon
                  icon={faLinkedin}
                  size={isMobile ? "1x" : "2x"}
                />
              </a>
            </Link>
            <Link href="https://id.pinterest.com/projectresa11/" passHref>
              <a target="_blank" className={styles.socialIcon}>
                <FontAwesomeIcon
                  icon={faPinterest}
                  size={isMobile ? "1x" : "2x"}
                />
              </a>
            </Link>
          </div>
          <div className={styles.download}>
            <a className={styles.btnDownload}>
              Download CV <FontAwesomeIcon icon={faDownload} size="1x" />
            </a>
          </div>
          <div className={styles.copyright}>
            &copy; {date} All Rights Reserved.
          </div>
        </div>
        <div className={styles.content}>
          <Menu
            onClick={() => setActiveMenu(!activeMenu)}
            active={activeMenu}
          ></Menu>
          {children}
        </div>
      </div>
    </section>
  );
};

export default Container;
